### ISSUE TITLE
core: Improve attributes API

### ISSUE THREAD

**Issue by robin-nitrokey** [trussed-dev/littlefs2#75]
See the discussion in https://github.com/trussed-dev/littlefs2/pull/73.

**Comment by robin-nitrokey** [comment]
I see three options to solve this issue:
1. Introduce an improved API for this feature now.  But this is not trivial:  How should we handle cases where the attribute does not fit into the buffer?  How can we provide a more user-friendly API, e. g. with `heapless::Vec`?
2. Remove the feature from core and bring it back once we know how the API should look like.  This would be a breaking change now for Trussed, and it would be a breaking change for littlefs2-core once we re-introduce it.
3. Just keep the current implementation.  While the API is not great, it at least ensures that data is not truncated silently, and only code that actually uses the feature has to pay the price of the large buffer size.

I would currently prefer to go with (3) to keep things simple and to move forward with the littlefs2-core crate.  If we come up with a better API in the future, introducing it would be a breaking change both in (2) and (3).

@sosthene-nitrokey What do you think?

**Comment by sosthene-nitrokey** [comment]
I think we can just expose a low-level API in `core` that has the same shape as the upstream lfs API. (so taking a buffer, returning a `usize` of the length of the attribute on disk), and maybe expose the `LFS_ATTR_MAX` value, but I don't think `core` needs to have abstractions that would lock us in this API.

If  we have the low-level abstraction we can still implement the "nicer" API with the current buffer on top of it, but not force its use.

**Comment by robin-nitrokey** [comment]
My problem with the low-level API is that it normally such APIs return the number of bytes written, not the number of bytes available. We could instead return something like this to avoid the potential confusion:

```
struct Attribute<'a> {
    data: &'a [u8],
    total_size: usize,
}

**Comment by sosthene-nitrokey** [comment]
That would look good to me.
